#!/usr/bin/env python3
"""
USF BIOS - Cython Compilation Script
Compiles Python source files to native .so files for code protection.
Copyright (c) US Inc. All rights reserved.
"""
import os
import sys
from distutils.core import setup
from Cython.Build import cythonize


def get_py_files(directory):
    """Get all .py files except __init__.py"""
    py_files = []
    for root, dirs, files in os.walk(directory):
        # Skip __pycache__ and hidden directories
        dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']
        for file in files:
            if file.endswith('.py') and file != '__init__.py':
                py_files.append(os.path.join(root, file))
    return py_files


def compile_directory(source_dir):
    """Compile all Python files in directory to .so"""
    py_files = get_py_files(source_dir)
    if not py_files:
        print(f"No Python files to compile in {source_dir}")
        return
    
    print(f"Compiling {len(py_files)} files in {source_dir}...")
    
    # Compile with Cython
    try:
        setup(
            ext_modules=cythonize(
                py_files,
                compiler_directives={
                    'language_level': '3',
                    'boundscheck': False,
                    'wraparound': False,
                },
                quiet=True
            ),
            script_args=['build_ext', '--inplace']
        )
    except Exception as e:
        print(f"Error compiling {source_dir}: {e}")
        sys.exit(1)
    
    # Remove source .py files (keep __init__.py)
    for py_file in py_files:
        if os.path.exists(py_file):
            os.remove(py_file)
            print(f"  Removed source: {py_file}")
    
    # Remove .c files generated by Cython
    for root, dirs, files in os.walk(source_dir):
        for file in files:
            if file.endswith('.c'):
                os.remove(os.path.join(root, file))


def minimize_init_files(base_dir):
    """Make __init__.py files minimal - keep only necessary imports"""
    for root, dirs, files in os.walk(base_dir):
        for file in files:
            if file == '__init__.py':
                filepath = os.path.join(root, file)
                try:
                    with open(filepath, 'r') as f:
                        content = f.read()
                    # Keep only imports and __all__ definitions
                    lines = [l for l in content.split('\n') 
                             if l.strip().startswith(('from ', 'import ', '__all__', '#'))]
                    with open(filepath, 'w') as f:
                        f.write('\n'.join(lines) + '\n' if lines else '# USF BIOS\n')
                except Exception as e:
                    print(f"Warning: Could not process {filepath}: {e}")


if __name__ == '__main__':
    print("=" * 60)
    print("  USF BIOS - Cython Compilation")
    print("  Compiling Python to native .so files...")
    print("=" * 60)
    
    # Compile directories
    compile_directory('/compile/usf_bios')
    compile_directory('/compile/web/backend/app')
    
    # Minimize __init__.py files
    minimize_init_files('/compile')
    
    print("=" * 60)
    print("  Compilation complete!")
    print("=" * 60)
